### ISSUE TITLE
Clipped polygon is incorrect

### ISSUE THREAD

**Issue by lhviet** [angelswing-team/volume-calculator-for-dsm#4]
The progam clips/cuts the image for volume calculating based on a WKT (well-known-text) polygon.
However, testing results point out that the clipped region is imprecise.

The test result (clipped images) is in the link below:
https://docs.google.com/spreadsheets/d/1J3nusoqYMRisPixA7XqrSIiFvFcaA1VNUqeV3GigcmU/edit?usp=sharing

**Comment by lhviet** [comment]
@Ailrun 
After fixed in PR #5 , I got another error in `clip.py`
```
ValueError: shape mismatch: objects cannot be broadcast to a single shape
```
Will investigate now, just let you know.

**Comment by Ailrun** [comment]
@lhviet ??? there is no line 265 in `clip.py`...

**Comment by lhviet** [comment]
@Ailrun 
Sorry, line 111
```
mask = np.fromstring(raster_poly.tobytes(), dtype=np.int8).reshape(raster_poly.im.size[1], raster_poly.im.size[0])
```
Do you think an Extent size **(285, 315)**
```raster_size = (ext_bound_x + 1, ext_bound_y + 1)``` will make a raster with size **(286, 316)** and lead to mist-match shape?

**Comment by lhviet** [comment]
FYI,
In case I keep the same size of the raster
```
raster_size = (ext_bound_x, ext_bound_y)
```
, another error will be thrown like this `IndexError: index 315 is out of bounds for axis 1 with size 315`

**Comment by Ailrun** [comment]
@lhviet Could you give me the result of `np.fromstring(raster_poly.tobytes(), dtype=np.int8).shape`?

**Comment by lhviet** [comment]
Just print it out like this:
`print(f'shape = {np.fromstring(raster_poly.tobytes(), dtype=np.int8).shape !r}')`

Do you have time to check?
If not I suggest to use the simple solution I suggested before first: decrease the polygon point 1 unit to keep it inside of the Extent.

**Comment by Ailrun** [comment]
@lhviet I mean, where did you check the codes? In the server? or in your local machine? If you run those in local machine, which .tif do you use?

**Comment by lhviet** [comment]
@Ailrun on my local machine
WKT: content `lake` in https://dev.ondronemap.com/project/118/content
```"POLYGON ((14351228.074714396 4262098.241802971,14351244.496732192 4262103.31769938,14351255.544271436 4262088.687174435,14351282.118082052 4262100.929042247,14351313.469206935 4262082.118367314,14351275.847857075 4262043.601271032,14351260.620167846 4262024.790596103,14351255.842853578 4262008.66716045,14351242.4066572 4262012.548728292,14351240.316582208 4262027.477835377,14351234.942103656 4262030.165074653,14351229.567625107 4262052.558735283,14351234.344939372 4262056.440303125))"```

TIF: DSM of 1140
[1140_r03.zip](https://github.com/angelswing-team/volume-calculator-for-dsm/files/2295875/1140_r03.zip)

**Comment by lhviet** [comment]
@Ailrun 
Sorry I gave you wrong number, please re-check info:
`raster_poly size = (286, 316)`
`shape (90376,)`
ERROR: `ValueError: shape mismatch: objects cannot be broadcast to a single shape`

**Comment by Ailrun** [comment]
@lhviet It occurs in line 114, then it's trivial.
In https://github.com/angelswing-team/volume-calculator-for-dsm/blob/a23e334ad0e2ef83c1b6df6bd8cc7d188532acf4/src/clip.py#L65-L69
size of `clipped_arr` is smaller than what we want, since python's `:` is exclusive.

**Comment by lhviet** [comment]
Do you have any idea to fix it?

**Comment by Ailrun** [comment]
@lhviet I also add a solution to previous comment. Sorry for frequent editing.

**Comment by Ailrun** [comment]
@lhviet Ye it works as far as I tested.

**Comment by Ailrun** [comment]
The result of my code.
![image](https://user-images.githubusercontent.com/12473268/44247222-d1255180-a1b0-11e8-86a4-b8bb2ecc7459.png)
